---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: okd-release-pipeline
spec:
  params:
    - description: The URL for the release controller to use
      name: release-controller
      type: string
      default: "https://origin-release.ci.openshift.org"
    - description: The release stream to use (e.g., 4.12.0-0.okd, 4.12.0-0.okd-scos)
      name: release-stream
      type: string
    - description: The app.ci imagestream to use for tagging (e.g., release or release-scos)
      name: release-imagestream
      type: string
    - description: The content mirror destination
      name: content-mirror-pushspec
      type: string
      default: "quay.io/zzlotnik/scos-content"
    - description: The release mirror destination
      name: release-mirror-pushspec
      type: string
      default: "quay.io/zzlotnik/scos-release"
    - description: The GitHub org/repo to release to
      name: github-org-repo
      type: string
      default: "cheesesashimi/okd-release-test"
    - description: Determines if the release should be tagged latest
      type: string
      name: is-release-latest
      default: "false"
    - name: enable-notifications
      type: string
      default: "false"
    - name: matrix-room
      description: room id (in the format !<ROOM_ID>:<SERVER_NAME>)
      type: string
      default: "!nStsazaBvZCZQHPWTY:fedoraproject.org"
    - name: matrix-endpoint
      description: endpoint to connect to
      type: string
      default: "matrix.org"
    - name: matrix-secret
      description: kubernetes secret containing the token to post messages
      type: string
      default: "okd-matrix-bot-auth"
  tasks:
    - name: pick-release
      taskRef:
        name: pick-release
      params:
        - name: release-controller
          value: $(params.release-controller)
        - name: release-stream
          value: $(params.release-stream)
    - name: verify-release
      taskRef:
        name: gpg-verify-release
      params:
        - name: release-digest
          value: $(tasks.pick-release.results.release-digest)
      runAfter:
        - pick-release
    - name: prepare-binaries
      taskRef:
        name: prepare-release-binaries
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: release-pullspec
          value: $(tasks.mirror.results.mirrored-pullspec)
        - name: gpg-signing-key
          value: okd-release-gpg-signing-key
        - name: gpg-key-id
          value: maintainers@okd.io
      runAfter:
        - mirror
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: mirror
      taskRef:
        name: mirror-release
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: release-pullspec
          value: $(tasks.pick-release.results.release-pullspec)
        - name: image-push-secret-name
          value: okd-quay-pull-secret
        - name: release-mirror-pushspec
          value: $(params.release-mirror-pushspec)
        - name: content-mirror-pushspec
          value: $(params.content-mirror-pushspec)
      runAfter:
        - verify-release
    - name: prepare-release-notes
      taskRef:
        name: prepare-release-notes
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: mirrored-release-pullspec
          value: $(tasks.mirror.results.mirrored-pullspec)
      runAfter:
        - mirror
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: get-github-access-token
      params:
        - name: github-app-id
          value: '309584'
        - name: github-app-installation-id
          value: '35633111'
        - name: githubapp-secret-name
          value: okd-githubapp-auth
      taskRef:
        kind: Task
        name: get-github-access-token
      runAfter:
        - prepare-binaries
        - prepare-release-notes
        - mirror
    - name: create-github-release
      taskRef:
        name: create-github-release
      params:
        - name: token
          value: $(tasks.get-github-access-token.results.githubapp-token)
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: github-org-repo
          value: $(params.github-org-repo)
        - name: is-latest
          value: $(params.is-release-latest)
      runAfter:
        - get-github-access-token
      workspaces:
        - name: release-binaries
          workspace: release-binaries
    - name: update-release-channel
      taskRef:
        name: update-release-channel
      params:
        - name: release-name
          value: $(tasks.pick-release.results.release-name)
        - name: mirrored-release-pullspec
          value: $(tasks.mirror.results.mirrored-pullspec)
        - name: release-imagestream
          value: $(params.release-imagestream)
        - name: ci-cluster-secret-name
          value: okd-prow-sa-auth
      runAfter:
        - create-github-release
  finally:
    - name: notify-matrix
      params:
        - name: matrix-secret
          value: $(params.matrix-secret)
        - name: endpoint
          value: $(params.matrix-endpoint)
        - name: room
          value: $(params.matrix-room)
        - name: message
          value: "PipelineRun $(context.pipelineRun.name) - $(params.release-stream): $(tasks.status)"
      when:
        - input: $(params.enable-notifications)
          operator: in
          values: ["true"]
      taskRef:
        kind: Task
        name: notify-matrix
  workspaces:
    - name: release-binaries
