apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: okd-release-next-pipelinerun-
spec:
  params:
  - name: content-mirror-pushspec
    value: quay.io/okd/scos-content
  - name: enable-notifications
    value: "true"
  - name: github-org-repo
    value: okd-project/okd
  - name: is-release-latest
    value: "false"
  - name: matrix-endpoint
    value: matrix.org
  - name: matrix-room
    value: '!nStsazaBvZCZQHPWTY:fedoraproject.org'
  - name: matrix-secret
    value: okd-matrix-bot-auth
  - name: release-controller
    value: https://origin-release.ci.openshift.org
  - name: release-imagestream
    value: release-scos-next
  - name: release-mirror-pushspec
    value: quay.io/okd/scos-release
  - name: release-stream
    value: 4.22.0-0.okd-scos-nightly
  - name: target-release-stream
    value: 4-scos-next
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: host-192-168-111-72
  pipelineRef:
    name: okd-release-pipeline
  timeouts:
    pipeline: 4h0m0s
  workspaces:
  - name: release-binaries
    persistentVolumeClaim:
      claimName: pipeline-release-next-pvc

