oc apply -f sa.yaml
oc apply -f cluster-role.yaml
oc apply -f crb.yaml
oc apply -f task.yaml
oc apply -f pipeline.yaml
oc apply -f trigger-template.yaml
oc apply -f trigger-binding.yaml
oc apply -f event-listener.yaml
oc apply -f cronjob.yaml