oc delete -f cronjob.yaml
oc delete -f event-listener.yaml
oc delete -f trigger-binding.yaml
oc delete -f trigger-template.yaml
oc delete -f pipeline.yaml
oc delete -f task.yaml
oc delete -f crb.yaml
oc delete -f cluster-role.yaml
oc delete -f sa.yaml
