apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-trigger-cluster-command
  namespace: okd-coreos
spec:
  suspend: false 
  schedule: "0 5 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl-trigger
              image: curlimages/curl:latest
              command: ["/bin/sh"]
              args:
                - "-c"
                - |
                  echo "[INFO] Triggering EventListener..."
                  curl -X POST \
                  http://el-cluster-command-listener.okd-coreos.svc.cluster.local:8080 \
                  -H 'Content-Type: application/json' \
                  -d '{"message":"trigger"}'
