apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cluster-command-template
  namespace: okd-coreos
spec:
  params:
  - name: trigger-source
<<<<<<< HEAD
  - name: next
    default: "false"
  - name: stable
    default: "false"
  - name: next-yaml
    default: "https://raw.githubusercontent.com/okd-project/okd-release-pipeline/main/environments/moc/pipelineruns/okd-release-next-pipelinerun.yaml"
  - name: stable-yaml
    default: "https://raw.githubusercontent.com/okd-project/okd-release-pipeline/main/environments/moc/pipelineruns/okd-release-stable-pipelinerun.yaml"
=======
>>>>>>> 22eeafa7765dbbe0ad86379e4993ceb4d0c2e604
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cluster-command-run-
      spec:
        serviceAccountName: tekton-cluster-access
        pipelineRef:
          name: cluster-command-pipeline
<<<<<<< HEAD
        params:
        - name: next
          value: $(tt.params.next)
        - name: stable
          value: $(tt.params.stable)
        - name: next-yaml
          value: $(tt.params.next-yaml)
        - name: stable-yaml
          value: $(tt.params.stable-yaml)
=======
>>>>>>> 22eeafa7765dbbe0ad86379e4993ceb4d0c2e604
